import pytest

from articlenizer import articlenizer

def test_prepro_pipeline():
    s = 'Testing the entire preprocessing pipeline on a real article (f)=∇∑ excerpt. Cells were lysed in 1X RIPA Buffer (Cell Signaling Technology) supplemented with 1 mM PMSF and a protease inhibitor cocktail (Sigma-Aldrich). Lysates were cleared by centrifugation (10 min at 16,000 x g at 4ºC). 20-80 μg of protein per sample was loaded onto 10% or gradient SDS-polyacrylamide gels and separated by electrophoresis. Proteins were transferred to PVDF or nitrocellulose membranes, which were then blocked with 5% milk for 1 hr at room temperature. Membranes were then probed with primary antibodies diluted in 1-5% milk or BSA for 3 hrs at room temperature or overnight at 4°C: rabbit anti-DYNC2LI1 [26] (1:200; LIC3), rabbit anti-WDR34 (1:200; Abcam ab81030), rabbit anti-DYNC2H1 [26] (1:150; Dynein HC2), rabbit anti-GAPDH (1:1,000; 14C10; Cell Signaling Technology #2118), mouse anti-β-tubulin (1:10,000; GTU-88; Abcam ab11316), mouse anti-β-tubulin (1:5000; Sigma T9026), and goat anti-GLI3 (1 μg mL; R&D Systems AF3690). After extensive washing, membranes were incubated with HRP-conjugated or fluorescent secondary antibodies and the signal was captured on film or in an Odyssey system (Licor). Protein amounts were quantified from scanned blots using ImageJ (NIH). Full scans of Western blot data are included in Supplementary Fig. 6.'
    s = articlenizer.get_tokenized_sentences(s)
    assert s == [
        ['Testing', 'the', 'entire', 'preprocessing', 'pipeline', 'on', 'a', 'real', 'article', 'formtok', 'excerpt', '.'], 
        ['Cells', 'were', 'lysed', 'in', '1X', 'RIPA', 'Buffer', '(', 'Cell', 'Signaling', 'Technology', ')', 'supplemented', 'with', '1', 'mM', 'PMSF', 'and', 'a', 'protease', 'inhibitor', 'cocktail', '(', 'Sigma', '-', 'Aldrich', ')', '.'], 
        ['Lysates', 'were', 'cleared', 'by', 'centrifugation', '(', '10', 'min', 'at', '16,000', 'x', 'g', 'at', '4oC', ')', '.'], 
        ['20', '-', '80', 'μ', 'g', 'of', 'protein', 'per', 'sample', 'was', 'loaded', 'onto', '10', '%', 'or', 'gradient', 'SDS', '-', 'polyacrylamide', 'gels', 'and', 'separated', 'by', 'electrophoresis', '.'], 
        ['Proteins', 'were', 'transferred', 'to', 'PVDF', 'or', 'nitrocellulose', 'membranes', ',', 'which', 'were', 'then', 'blocked', 'with', '5', '%', 'milk', 'for', '1', 'hr', 'at', 'room', 'temperature', '.'], 
        ['Membranes', 'were', 'then', 'probed', 'with', 'primary', 'antibodies', 'diluted', 'in', '1', '-', '5', '%', 'milk', 'or', 'BSA', 'for', '3', 'hrs', 'at', 'room', 'temperature', 'or', 'overnight', 'at', '4', '°', 'C', ':', 'rabbit', 'anti', '-', 'DYNC2LI', '1', '[26]', '(', '1', ':', '200', ';', 'LIC', '3', ')', ',', 'rabbit', 'anti', '-', 'WDR', '34', '(', '1', ':', '200', ';', 'Abcam', 'ab', '81030', ')', ',', 'rabbit', 'anti', '-', 'DYNC2H', '1', '[26]', '(', '1', ':', '150', ';', 'Dynein', 'HC', '2', ')', ',', 'rabbit', 'anti', '-', 'GAPDH', '(', '1', ':', '1,000', ';', '14C', '10', ';', 'Cell', 'Signaling', 'Technology', '#', '2118', ')', ',', 'mouse', 'anti', '-', 'β', '-', 'tubulin', '(', '1', ':', '10,000', ';', 'GTU', '-', '88', ';', 'Abcam', 'ab', '11316', ')', ',', 'mouse', 'anti', '-', 'β', '-', 'tubulin', '(', '1', ':', '5000', ';', 'Sigma', 'T9026', ')', ',', 'and', 'goat', 'anti', '-', 'GLI', '3', '(', '1', 'μ', 'g', 'mL', ';', 'R&D', 'Systems', 'AF', '3690', ')', '.'], 
        ['After', 'extensive', 'washing', ',', 'membranes', 'were', 'incubated', 'with', 'HRP', '-', 'conjugated', 'or', 'fluorescent', 'secondary', 'antibodies', 'and', 'the', 'signal', 'was', 'captured', 'on', 'film', 'or', 'in', 'an', 'Odyssey', 'system', '(', 'Licor', ')', '.'], 
        ['Protein', 'amounts', 'were', 'quantified', 'from', 'scanned', 'blots', 'using', 'ImageJ', '(', 'NIH', ')', '.'], 
        ['Full', 'scans', 'of', 'Western', 'blot', 'data', 'are', 'included', 'in', 'Supplementary', 'Fig', '.', '6', '.']
    ]
